include:
- project: 'ci-tools/container-image-ci-templates'
  file: 'kaniko-image.gitlab-ci.yml'
  ref: master
- project: 'ci-tools/container-image-ci-templates'
  file: 'helm.gitlab-ci.yml'
  ref: master

image:
  rules:
  - if: $CI_COMMIT_TAG
    variables:
      PUSH_IMAGE: "true"
  - if: $CI_COMMIT_BRANCH
  extends: .build_kaniko
  variables:
    REGISTRY_IMAGE_PATH: "registry.cern.ch/rvasek/kaniko-mirror-test:$CI_COMMIT_TAG"
    CONTEXT_DIR: "."
    DOCKER_FILE_NAME: "image/Dockerfile"
  image: golang:1.17
  before_script:
    - export PATH="${GOPATH}/bin:${PATH}"
  after_script:
    - rm -rf vendor
  script:
    - make

chart:
  rules:
  - if: $CI_COMMIT_TAG
    variables:
      PUSH_IMAGE: "true"
  extends: .deploy_helm
  variables:
    REGISTRY_PATH: registry.cern.ch/chartrepo/rvasek
