# Default values for hello-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.cern.ch/rvasek/kaniko-mirror-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.0"

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
